import Head from "next/head";
import { Inter } from "@next/font/google";
import Slide from "../components/partials/Slide";
import { Cards } from "../components/ui/Cards";
import { cards, newsData } from "../test/datas";
import { useEffect, useState } from "react";
import Spinner from "../components/ui/Spinner";
import { LeftSide, RightSide } from "../components/ui/Ui";
import Index from "../components/pages/Index";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    setIsReady(true);
  }, []);

  if (!isReady) return <Spinner />;
  return (
    <>
      <Head>
        <title>Colegiado do Curso da Engenharia Elétrica </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="">
        <Index />
      </main>
    </>
  );
}
